baseurl = "https://www.kashifjournal.com/"
DefaultContentLanguage = "ar"
theme = "hugo-xmag"
googleAnalytics = "UA-111470283-2"
disqusShortname = "kashifjournal"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "â©"
hasCJKLanguage = true
enableEmoji = true
paginate = 6

[languages]
  [languages.ar]
    title = "صحيفة كاشف"
    weight = 1
  [languages.en]
    title = "KAHIF Journal"
    weight = 2

[params.banner]
    src = "/banner_new.png"
    alt = ""

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]] 
    name = "Tags"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"
    
[[menu.main]]
    name = "الرئيسية"
    url = "/"
    weight = 1
[[menu.main]]
    name = "من نحن"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "التصنيفات"
    url = "/categories/"
    weight = 3
    
[[menu.main.ar]] 
    name = "وسوم"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "اشترك"
    url = "/index.xml"
    
    
[params]
    description = "A Saudi Data Journal"
    summary_length = 300
    github_edit = "/"
    footer = "&copy; Kashif 2018 | [Github](https://github.com/Ammar-K/journal) | [Twitter](https://twitter.com/kashifjournal)"

[params.text]
    back = "&larr; Back to Home"
    edit = "Edit this page &rarr;"
    truncated = "&hellip;"
    
[outputs]
  home = ["HTML", "RSS", "JSON"]
